import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#080812',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  bgShape1: {
    position: 'absolute',
    width: width * 1.2,
    height: width * 1.2,
    borderRadius: width * 0.6,
    backgroundColor: 'rgba(0, 50, 100, 0.3)',
    top: -height * 0.4,
    left: -width * 0.3,
  },
  bgShape2: {
    position: 'absolute',
    width: width * 0.8,
    height: width * 0.8,
    borderRadius: 20,
    backgroundColor: 'rgba(10, 10, 60, 0.25)',
    bottom: -height * 0.2,
    right: -width * 0.2,
    transform: [{ rotate: '45deg' }],
  },
  card: {
    width: width * 0.9,
    padding: 28,
    borderRadius: 24,
    backgroundColor: 'rgba(15, 15, 30, 0.5)',
    borderWidth: 1,
    borderColor: 'rgba(0, 120, 200, 0.5)',
    backdropFilter: 'blur(18px)',
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#e0e8ff',
    marginBottom: 26,
    textAlign: 'center',
    textShadowColor: '#005577',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  title2:{
	fontSize: 23,
    color: '#e0e8ff',
    marginBottom: 20,
    textAlign: 'center',
    textShadowColor: '#005577',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
	marginHorizontal: 16,
  },
  commonText: {
	fontSize: 16,
	color: '#e0e8ff',
	marginBottom: 12,

	textAlign: 'center',
	textShadowColor: '#005577',
	textShadowOffset: { width: 0, height: 0 },

	textShadowRadius: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(0, 100, 180, 0.6)',
    borderRadius: 14,
    padding: 16,
    marginBottom: 22,
    color: '#eef2ff',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    shadowColor: '#0088cc',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
  },
  button: {
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: 'rgba(0, 100, 180, 0.6)',
    shadowColor: '#0088cc',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 12,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#e0fffa',
    textShadowColor: '#005577',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
});
